packages:
  - "."

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@playwright/browser-chromium"
  - "@sentry/cli"
  - "@swc/core"
  - core-js
  - esbuild
  - protobufjs
  - sharp
  - supabase
  - unix-dgram
  - unrs-resolver
