/**
 * ESLint Report Parser
 * Reads the JSON report generated by ESLint and prints it grouped by file.
 * Optionally saves the human-readable output to a file.
 * Usage: node scripts/parse-eslint.js [path/to/eslint.json] [--output path/to/report.txt]
 */

const fs = require('fs');
const path = require('path');

function printLintSummary(reportPath, options = {}) {
    if (!fs.existsSync(reportPath)) {
        console.log(`  ⚠️  ESLint report not found at ${reportPath}`);
        return;
    }

    let data;
    try {
        const raw = fs.readFileSync(reportPath, 'utf8');
        const jsonStart = raw.indexOf('[');
        if (jsonStart === -1) {
            console.log('  ⚠️  ESLint report does not contain a JSON array');
            return;
        }
        const jsonEnd = raw.lastIndexOf(']');
        if (jsonEnd === -1 || jsonEnd < jsonStart) {
            console.log('  ⚠️  ESLint report contains an incomplete JSON array');
            return;
        }
        data = JSON.parse(raw.slice(jsonStart, jsonEnd + 1));
    } catch (e) {
        console.log('  ⚠️  Could not parse eslint.json');
        return;
    }

    const errors = {};
    const warnings = {};
    let totalErrors = 0;
    let totalWarnings = 0;
    let filesWithIssues = 0;

    const fileGroupings = [];
    let outputBuffer = "";

    const log = (msg) => {
        console.log(msg);
        outputBuffer += msg + "\n";
    };

    for (const file of data) {
        if (file.messages.length === 0) continue;
        filesWithIssues++;

        const relativeFilePath = path.relative(process.cwd(), file.filePath);
        let fileOutput = `\n📄 ${relativeFilePath}\n`;

        for (const msg of file.messages) {
            const isError = msg.severity === 2;
            const rule = msg.ruleId || '(parse error)';

            if (isError) {
                errors[rule] = (errors[rule] || 0) + 1;
                totalErrors++;
            } else {
                warnings[rule] = (warnings[rule] || 0) + 1;
                totalWarnings++;
            }

            const type = isError ? '🔴 ERR' : '🟡 WRN';
            const position = `${msg.line || 0}:${msg.column || 0}`;

            fileOutput += `     ${type}  [${position.padEnd(7)}]  ${msg.message} (${rule})\n`;
        }
        fileGroupings.push(fileOutput);
    }

    const pad = (n) => n.toString().padStart(5);

    if (filesWithIssues > 0) {
        log(`\n  ┌─ ESLINT: ISSUES BY FILE (${filesWithIssues} files) ───────────────┐`);
        fileGroupings.forEach(out => {
            log(out.trimEnd());
            log('');
        });
        log(`  └──────────────────────────────────────────────────────────────────┘\n`);
    }

    if (totalErrors > 0) {
        log(`  ┌─ ERRORS (${totalErrors} total) ──────────────────────────────────┐`);
        Object.entries(errors)
            .sort((a, b) => b[1] - a[1])
            .forEach(([rule, count]) =>
                log(`  │ ${pad(count)}  ${rule}`)
            );
        log(`  └──────────────────────────────────────────────────────────────────┘`);
    } else {
        log(`  ✅ No ESLint errors!`);
    }

    if (totalWarnings > 0) {
        log(`\n  ┌─ WARNINGS (${totalWarnings} total) ────────────────────────────────┐`);
        Object.entries(warnings)
            .sort((a, b) => b[1] - a[1])
            .forEach(([rule, count]) =>
                log(`  │ ${pad(count)}  ${rule}`)
            );
        log(`  └──────────────────────────────────────────────────────────────────┘`);
    }

    if (options.outputFile) {
        const outputFile = path.isAbsolute(options.outputFile)
            ? options.outputFile
            : path.join(process.cwd(), options.outputFile);

        fs.writeFileSync(outputFile, outputBuffer.replace(/\x1B\[[0-9;]*[a-zA-Z]/g, '')); // Strip ANSI codes
    }
}

if (require.main === module) {
    const reportPath = process.argv.find(arg => arg.endsWith('.json')) || path.join(process.cwd(), 'reports', 'eslint.json');
    const outputIdx = process.argv.indexOf('--output');
    const outputFile = outputIdx !== -1 ? process.argv[outputIdx + 1] : null;

    printLintSummary(reportPath, { outputFile });
}

module.exports = { printLintSummary };
